import { Badge } from "@/components/badge"
import { Title } from "@/components/title"
import { projects } from "./data/projectsData"

export const Projects = () => {
  return (
    <section
      id="projects"
      className="
        flex
        flex-col
        gap-8
        mt-32
        xl:mt-48
        px-8
    ">
      <div
        data-aos="fade-up"
        data-aos-duration="1000"
        className="
        flex
        flex-col
        gap-4
        xl:justify-end 
        xl:items-end
      ">
        <Badge content="My Work" />
        <Title
          className="
          xl:text-end 
          text-center
          text-[23px]
          sm:max-lg:text-[32px]
          lg:text-[45px]
        ">
          Featured Projects
        </Title>
      </div>
      {projects.map((project) => (
        <div
          key={project.name}
          className="
          mt-12
          md:mt-32
          flex
          flex-col
          md:flex-row
          justify-between
          items-start
          overflow-hidden
          gap-16        
          ">
          <div
            data-aos="fade-up"
            data-aos-duration="1000"
            className="
            flex
            flex-col
            gap-4
            md:gap-8
          ">
            <div
              className="
              flex
              flex-col
              gap-4
      ">
              <div
                className="
              w-max
              py-1
              px-8 
              badge-gradient
              border
              border-[#404A47]
              rounded-full
              flex
              flex-col
    ">
                <span
                  className="
                badge-text 
                text-[8px]
                sm:max-lg:text-[11px]
                lg:text-[16px]
              ">
                  {project.badge}
                </span>
              </div>
              <h1
                className="
                title-gradient
              font-medium
              leading-normal
              text-[23px]
              sm:max-lg:text-[32px]
              lg:text-[45px]
              transition-all
            ">
                {project.name}
              </h1>
            </div>
            <p
              className="
              text-secondary
              text-[11px]
              sm:max-lg:text-[16px]
              lg:text-[23px]
              w-[25ch]
          ">
              {project.description}
            </p>
            <div
              className="
              flex 
              flex-row 
              gap-2
            ">
              <a
                className="
                w-max
                flex
                flex-row
                items-center
                text-white
                gap-2
                py-1
                px-2
                md:py-2
                md:px-4
                border-[#E1F8FFB2]
                border
                md:border-2
                rounded-lg
                transition
                duration-300
                opacity-50
                hover:opacity-100
                "
                target="_a"
                href={project.githubLink}
              >
                <span className="
                text-[8px] 
                sm:max-lg:text-[11px] 
                lg:text-[16px] 
                ">
                  Visit Repo
                </span>
                <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" className="svg-size">
                  <path fillRule="evenodd" d="M5.22 14.78a.75.75 0 0 0 1.06 0l7.22-7.22v5.69a.75.75 0 0 0 1.5 0v-7.5a.75.75 0 0 0-.75-.75h-7.5a.75.75 0 0 0 0 1.5h5.69l-7.22 7.22a.75.75 0 0 0 0 1.06Z" clipRule="evenodd" />
                </svg>
              </a>
              {project.livePreview &&
                <a
                  className="
                   w-max
                  flex
                  flex-row
                  items-center
                  text-white
                  gap-2
                  py-1
                  px-2
                  md:py-2
                  md:px-4
                  border-[#E1F8FFB2]
                  border
                  md:border-2
                  rounded-lg
                  transition
                  duration-300
                  opacity-50
                  hover:opacity-100
                  "
                  target="_a"
                  href={project.livePreview}
                >
                  <span className="
                  text-[8px] 
                  sm:max-lg:text-[11px] 
                  lg:text-[16px] 
                  ">
                    Visit Repo
                  </span>
                  <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" className="svg-size">
                    <path fillRule="evenodd" d="M5.22 14.78a.75.75 0 0 0 1.06 0l7.22-7.22v5.69a.75.75 0 0 0 1.5 0v-7.5a.75.75 0 0 0-.75-.75h-7.5a.75.75 0 0 0 0 1.5h5.69l-7.22 7.22a.75.75 0 0 0 0 1.06Z" clipRule="evenodd" />
                  </svg>
                </a>}
            </div>
          </div>
          {project.image}
        </div>
      ))}
    </section>
  )
}